[project]
name = "pytest-minimal-example"
version = "0.1.0"
description = "A minimal python project to showcase pytest functionalities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hypothesis>=6.136.4",
    "pytest>=8.4.1",
    "pytest-xdist>=3.8.0",
]
